config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :skip => :registrations
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'users/confirmations'}

  authenticated :user do
    root to: "users#show", as: :authenticated_user
    resource :billing, controller: 'billing'
    namespace :billing do
      resource :customer, controller: 'customer'
      resources :charges
      resource :plans
    end
    #resources :services, path:'console'
    
    namespace :services do
      post 'deploy', to: 'deploy'
      get 'status', to: 'status'
    end

    resource :users, path:'account', only: [:show, :update]
    namespace :users, path:'account' do
      # Change this to something else...
      get 'applications', controller: 'applications', action: 'get_user_applications'
      post 'applications', controller: 'applications', action: 'select_applications'
      get 'settings', to: 'settings'
      match 'provision', to: 'provision', via: [:post] #needs to be a post request
      get 'provision_status', action: 'current_provision_status'
    end
  end

  authenticated :admin do
    devise_for :admins, only: [:registrations], controllers: { registrations: 'admins/registrations' }
    root to: "admins#show", as: :authenticated_admin
    namespace :admins do
      get 'user_statuses', to: 'users_statuses'
      get 'chart_data', to: 'chart_data', action:'chart_data'
      get 'validations', to: 'domain_validations', action:'domain_validations'
      post 'validate', to: 'validate_domain', action: 'validate_domain'
      post 'invalidate', to: 'invalidate_domain', action: 'invalidate_domain'
      get 'builds', to: 'build_tickets', action:'build_tickets'
      get 'decoms', to: 'decom_tickets', action:'decom_tickets'
      post 'mark_build_complete', to: 'mark_build_complete', action:'mark_build_complete'
      post 'mark_decom_complete', to: 'mark_decom_complete', action:'mark_decom_complete'

      get 'centerview', to:'centerview'
      namespace :centerview do
        get 'environments', to: 'environments'
        get 'subscriptions', to: 'subscriptions'
        get 'servers', to: 'servers'
        get 'domains', to: 'domains'
        get 'states', to: 'states'
      end

      resource :concierge, controller: "concierge"
      mount Blazer::Engine, at: "blazer"
    end
  end

  namespace :rundeck do
    post 'start', to: 'start', action: 'start'
    post 'complete', to: 'complete', action: 'complete'
    post 'fail', to: 'fail', action: 'fail'
    resource :options, only: [:show, :update]
    resource :datapoints, only: [:show] do
      get 'environment', action: 'environment_job_info'
      get 'instance', action: 'instance_job_info'
      get 'migration', action: 'migration_job_info'
    end
  end

  # unauthenticated :user do
  #   root "staticpages#index"
  # end

  root 'staticpages#index'

  get 'about', to: 'staticpages#about'
  get 'alternatives', to: 'staticpages#alternatives'
  get 'consulting', to: 'consultations#index'
  get 'contact', to: 'staticpages#contact'
  get 'home', to: 'staticpages#index'
  get 'pricing', to: 'staticpages#pricing'
  get 'privacy', to: 'staticpages#privacy'
  get 'products', to: 'products#list'
  get 'terms', to: 'staticpages#terms'

  post 'contact', to: 'staticpages#create_contact', as: 'contact_informations'
  namespace :products, path: "products" do
    get 'all', to: 'all'
  end
  resources :products, except: [:index]

  scope 'cases', module: "staticpages/cases", as: "cases" do
    get 'index', to: 'index'
    get 'students', to: 'students'
    get 'developers', to: 'developers'
    get 'projects', to: 'projects'
    get 'owners', to: 'owners'
    get 'leads', to: 'leads'
  end


  # resource :support
  # External Sites
  get "/docs" => redirect("https://compositionalenterprises.ourcompose.com/bookstack/books"), :as => :docs
  get "/gitlab" => redirect("https://gitlab.com/compositionalenterprises"), :as => :gitlab
  get "/forum" => redirect("https://reddit.com/r/ourcompose"), :as => :forum
  get "/podcast" => redirect("https://ourcomposecast.com"), :as => :podcast
  get "/roadmap" => redirect("https://compositionalenterprises.ourcompose.com/kanboard/public/board/245d06ce519a4deba6131ea58a65afa9efc0e6de584e04b08a81c4115322"), :as => :roadmap
end

app/controllers/staticpages/cases_controller.rb
class Staticpages::CasesController < ApplicationController
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
    def index
    end

    def contact
        @contact = ContactInformation.new
        @subject = params[:subject]
        @description = params[:description]
    end

    def create_contact
        @contact = ContactInformation.new(contact_params)
        if @contact.valid? && @contact.save
            redirect_to root_url, flash: { success: "Thank you for reaching out! We will reach out to you as soon as we can! Check your email to confirm we recieved this contact!"}
            MatrixNotifyJob.perform_later(contact_params[:subject], "#{contact_params[:email].to_s} -- #{contact_params[:description].to_s}")
            ContactMailer.with(contact: @contact).contact_received.deliver_later
        else
            flash[:alert] = "Please check that all the fields below are not empty and re-submit!"
            render:contact
        end
    end

    private 

    def contact_params
        params.require(:contact_information).permit(:phone_number, :first_name, :last_name, :email, :subject, :description)
    end

end

app/helpers/staticpages/cases_helper.rb
module Staticpages::CasesHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/staticpages/_footer.erb
<footer class="container" style="">
      <div class="row">
        <div class="col-12 col-md">
          <div class="row">
            <img class="img-responsive" style="max-width: 24px; max-height:24px;" src="<%= asset_pack_path('media/images/CircularLogoTransparent.png') %>" />
            <small class="d-block mt-1 ml-1 text-muted">© 2020</small>
          </div>
        </div>
        <div class="col-6 col-md">
          <h5>Services</h5>
          <ul class="list-unstyled text-small">
            <li><%= link_to "Products & Services", products_path, class:"text-muted" %></li>
            <li><%= link_to "Pricing", pricing_path, class:"text-muted" %></li>
            <li><%= link_to "Docs", docs_path, class:"text-muted" %></li>
            <li><%= link_to "Solutions", consulting_path, class:"text-muted" %></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>Resources</h5>
          <ul class="list-unstyled text-small">
            <li><%= link_to "Students", cases_students_path, class:"text-muted" %></li>
            <li><%= link_to "Developers", cases_developers_path, class:"text-muted" %></li>
            <li><%= link_to "Open Source Projects", cases_projects_path, class:"text-muted" %></li>
            <li><%= link_to "Small Business Owners", cases_owners_path, class:"text-muted" %></li>
            <li><%= link_to "Team Leads", cases_leads_path, class:"text-muted" %></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>About</h5>
          <ul class="list-unstyled text-small">
            <li><%= link_to "About Us", about_path, class:"text-muted" %></li>
            <li><%= link_to "Alternatives", alternatives_path, class:"text-muted" %></li>
            <li><%= link_to "Privacy", privacy_path, class:"text-muted" %></li>
            <li><%= link_to "Terms", terms_path, class:"text-muted" %></li>
            <li><%= link_to "Contact", contact_path, class:"text-muted" %></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>Community</h5>
          <ul class="list-unstyled text-small">
            <li><%= link_to "Podcast", podcast_path, class:"text-muted" %></li>
            <li><%= link_to "Forum", forum_path, class:"text-muted" %></li>
            <li><%= link_to "Gitlab", gitlab_path, class:"text-muted" %></li>
            <li><%= link_to "Feature Roadmap", roadmap_path, class:"text-muted" %></li>
          </ul>
        </div>
      </div>
</footer>

app/views/staticpages/_navbar_top.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <div class="container">
        <%= link_to root_url, class:"navbar-brand" do %>
            <img src="<%= asset_pack_path("media/images/LogoWithNameTransparent.png") %>" height="30" />
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <%= link_to "About", about_url, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Products & Services", products_url, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Pricing", pricing_url, class:"nav-link" %>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    More
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Use Cases", cases_index_path, class:"dropdown-item" %>
                <%= link_to "Solutions", consulting_path, class:"dropdown-item" %>
                <%= link_to "Contact", contact_path, class:"dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "Alternatives", alternatives_path, class:"dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "Documentation", docs_url, class:"dropdown-item" %>
                <%= link_to "Community", forum_url, class:"dropdown-item" %>
                <%= link_to "Podcast", podcast_url, class:"dropdown-item" %>
                <%= link_to "Gitlab", gitlab_url, class:"dropdown-item" %>
                <%= link_to "Feature Roadmap", roadmap_url, class:"dropdown-item" %>

                </div>
            </li>
        </ul>
        <div class="navbar-nav ml-auto">
            <%- if !user_signed_in? -%>
                <%= link_to "Sign up", new_user_registration_path, class:"nav-link" %>
                <%= link_to "Log in", new_user_session_path, class:"nav-link" %>
            <%- else -%>
                <%= render 'users/shared/account_dropdown' %>
            <%- end -%>
        </div>
    </div>
    </div>
</nav>

<!-- Flash Messages -->
<div class="container-fluid">
    <div class="row">
    <div class="col-sm-12">
        <% flash.each do |type, msg| %>
            <% if type == "notice" %>
                <div class="alert alert-success">
            <% elsif type == "alert" %>
                <div class="alert alert-danger">
            <% else %>
                <div class='alert alert-<%= "#{type}" %>'>
            <% end %>
            <a href="#" class="close" data-dismiss="alert">&#215;</a>
            <ul>
                <li>
                <%= msg %>
                </li>
            </ul>
            </div>
        <% end %>
    </div>
    </div>
</div>
<!-- End Flash Messages -->

app/views/staticpages/about.erb
<!-- Navigation -->
<%= render 'staticpages/navbar_top'%>

<!-- Header -->
<!-- Header -->
<header class="py-1 mb-4 about-header swirly-background" style="no-repeat center center; background-size: cover;">
<div class="container h-100">
    <div class="row h-100 align-items-center">
    <div class="col-lg-12">
        <h1 class="display-4 text-white mt-3 mb-2">About</h1>
        <p class="lead mb-5 text-white">OurCompose provides the best platform to help any sized organization or individual boost productivity and enhance organization.</p>
    </div>
    </div>
</div>
</header>

<!-- Page Content -->
<div class="container">

    <div class="row">
        <div class="col-md-12 mb-4">
            <h2>What We Do</h2>
            <hr>
            <p>We took a handful of open source applications and integrated them together into a product named OurCompose making it easy for anyone to deploy a suite of tools at the click of a button. When you sign up, we use OurCompose to build a server custom to your organization. The tools are then available for you and your organization to use.</p>
            <p>On top of the tools we provide, we wanted to create a knowledge bank of resources to help any business organize and manage everything from their IT tools to their finances and day-to-day operations. Check out our forums and public documentation for more!</p>
        </div>
    </div>
    <!-- /.row -->

    <div class="row">
        <div class="col-md-6 mb-5">
        <div class="card h-100">
            <div class="card-body">
                <h4 class="card-title">View Tools</h4>
                <p class="card-text">Our core set of tools for OurCompose include: Kanban, NextCloud, Bitwarden!</p>
            </div>
            <div class="card-footer">
                <%= link_to "Learn More about these Tools!", products_path, class:"btn btn-primary" %>
            </div>
        </div>
        </div>
        <div class="col-md-6 mb-5">
        <div class="card h-100">
            <div class="card-body">
                <h4 class="card-title">View Source</h4>
                <p class="card-text">If you prefer to manage your own infrastructure and support, we open sourced the tools and made them available for anyone to use on Gitlab</p>
            </div>
            <div class="card-footer">
                <a href="https://gitlab.com/compositionalenterprises" class="btn btn-primary">Go to Gitlab!</a>
            </div>
        </div>
        </div>
    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

<div style="padding-top:5%;">
    <%= render 'staticpages/footer' %>
</div>

app/views/staticpages/index.erb
<!-- Navigation -->
<%= render 'staticpages/navbar_top' %>

<div class="container-fluid">
<div class="row" style="min-height:96vh">
<div class="col-sm-6 my-auto offset-sm-1" style="">


<!-- Masthead -->
<div class="text-white text-center container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <img class="img-responsive" style="max-width: 99%;" src="<%= asset_pack_path('media/images/LogoWithNameTransparent.png') %>" />
        </div>
    </div>
</div>

<section class="features-icons bg-light text-center" style="padding-bottom: 0px;padding-top: 1rem;">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-xl-10 mx-auto">
                <%= javascript_pack_tag "index-typewriter.js" %>
                <h4 class="mb-4 font-weight-normal">
                    <div class="row text-center">
                        <div class="col-sm-12 text-center">OurCompose makes it easy to deploy:</div>
                    </div>
                    <div class="row justify-content-center">
                    <span class="typewrite flex" data-period="2000" data-type='[ "Storage Solutions", "Content Management Systems", "Project Management Software", "IT Operations Tooling", "Organization Management Tools" ]'>
                        <span class="wrap"></span>
                    </span>
                    </div>
                </h4>
            </div>
        </div>
    </div>
    </div>
</section>

<div class="col-sm-4 my-auto mx-auto">
    <div style="padding-bottom:5%; padding-top:1%;" id="suite" class="">
    <div class="container-fluid">
    <div class="col-sm-10">
    <span class="subtitle-1 small">Newsletter & Podcast</span>
        <!-- Begin Mailchimp Signup Form -->
        <div id="mc_embed_signup">
        <form action="https://ourcompose.us17.list-manage.com/subscribe/post?u=5ad50617f622ad67a5622b269&amp;id=a8561e41df" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate form-group" target="_blank" novalidate>
            <div id="mc_embed_signup_scroll">
            <h3 class="section-title-1 font-weight-bold" style="font-size: 28px;">Make it in the modern world without compromising anything</h3>
            <div class="mc-field-group">
                <label for="mce-FNAME">Name <small>(Optional)</small></label>
                <input type="text" value="" name="FNAME" class="form-control" id="mce-FNAME">
            </div>
            <div class="mc-field-group mb-1">
                <label for="mce-EMAIL">Email Address  <span class="asterisk text-danger"><small>*required</small></span>
                </label>
                <input type="email" value="" name="EMAIL" class="required email form-control" id="mce-EMAIL">
            </div>
            <div id="mce-responses" class="clear">
                <div class="response" id="mce-error-response" style="display:none"></div>
                <div class="response" id="mce-success-response" style="display:none"></div>
            </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
            <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_5ad50617f622ad67a5622b269_a8561e41df" tabindex="-1" value=""></div>
            <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button btn btn-primary mt-2"></div>
            </div>
        </form>
        </div>
        <!--End mc_embed_signup-->
    </div>
    </div>
</div>
</div>
</div>
</div>

<div style="padding-bottom:2%;" id="about-us">
  <div class="container">
  <div style="position:relative;overflow:hidden;width:100%;padding-top:56.25%">
      <iframe style="position:absolute;top:0;left:0;bottom:0;right:0;width:100%;height:100%;border:none;" src="https://www.youtube-nocookie.com/embed/videoseries?list=PLt92CQtzdbDIRZD6avCAaT_DRwQX8-tj6&autoplay=1&mute=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
  </div>
  </div>
</div>

<div style="padding-bottom:2%;" id="about-us">
  <div class="container">
    <div class="row">
    <div class="col-12 mb-1" style="margin-top:4rem !important;">
    <span class="subtitle-1 small">Next Steps</span>
    <h2 class="section-title-1 font-weight-bold">Where should we go next?</h2>
    </div>
    </div>
  <div class="row mt-2 col-sm-12">
      <div class="mt-1">
          <%= link_to "Deploy Services Now!", pricing_path, class:"btn btn-primary btn-xl js-scroll-trigger" %>
      </div>
      <div class="mt-1 ml-1">
          <%= link_to "Learn More!", about_path, class:"btn btn-secondary btn-xl js-scroll-trigger" %>
      </div>
  </div>
</div>
</div>

<div style="padding-bottom:2%;" id="suite">
<div class="container">
    <div class="row">
    <div class="col-12 mb-5" style="margin-top:4rem !important;">
    <span class="subtitle-1 small">Features</span>
    <h2 class="section-title-1 font-weight-bold">The OurCompose Suite</h2>
    </div>
    </div>
    <div class="row align-items-center mb-5">
    <div class="col-lg-6 mb-5 order-lg-2 mb-lg-0 aos-init aos-animate" data-aos="fade-right">
    <img src="<%= asset_pack_path("media/images/gitlab.png") %>" class="img-fluid img-shadow">
    </div>
    <div class="col-lg-5 mr-auto">
    <div class="mb-4">
    <h2 class="section-title-2">Innovative Technologies</h2>
    <p>At Compositional Enterprises, we value our time as much as you do. That's why we only use the best Free, Libre, and Open Source tools to produce our quality content and products.</p>
    </div>
    <div class="d-flex feature-v1">
    <span class="wrap-icon icon-users"></span>
    <div>
    <h3>Open Source</h3>
    <p>All the software we use and develop is open source and can be found on Gitlab!</p>
    </div>
    </div>
    <div class="d-flex feature-v1">
    <span class="wrap-icon icon-layers"></span>
    <div>
    <h3>Best in Class</h3>
    <p>We pick services that are constantly updated with practical use in mind.</p>
    </div>
    </div>
    </div>
    </div>
    <div class="row align-items-center">
    <div class="col-lg-6 mb-5 mb-lg-0 aos-init aos-animate" data-aos="fade-left">
    <img src="<%= asset_pack_path("media/images/portal.png") %>" alt="Image" class="img-fluid img-shadow">
    </div>
    <div class="col-lg-5 order-lg-1 ml-auto">
    <div class="mb-4">
    <h2 class="section-title-2">Powerful Apps</h2>
    <p>Our suite of applications will help any student, developer, project maintainer, small business owner or team lead push innovation past its current bounds.</p>
    </div>
    <div class="d-flex feature-v1">
    <span class="wrap-icon icon-cog"></span>
    <div>
    <h3>Many Features</h3>
    <p>From Runners to Portal, we offer many customizations to help you organize your workflow.</p>
    </div>
    </div>
    <div class="d-flex feature-v1">
    <span class="wrap-icon icon-bolt"></span>
    <div>
    <h3>Easy to use</h3>
    <p>We provide the tools to get any project off the ground and make it easy to onboard any new user.</p>
    </div>
    </div>
    </div>
    </div>
    <div class="row align-items-center mb-5">
    <div class="col-lg-6 mb-5 order-lg-2 mb-lg-0 aos-init aos-animate" data-aos="fade-right">
    <img src="<%= asset_pack_path("media/images/documentation.png") %>" class="img-fluid img-shadow">
    </div>
    <div class="col-lg-5 mr-auto">
    <div class="mb-4">
    <h2 class="section-title-2">Community Based</h2>
    <p>From server tech to workflow methodology, and desktop applications to budgeting, we share our own tips and tricks on how to make it in the modern world without compromising anything.</p>
    </div>
    <div class="d-flex feature-v1">
    <span class="wrap-icon icon-users"></span>
    <div>
    <h3>Documentation for all</h3>
    <p>Our documentation is for anyone who wants to use it.</p>
    </div>
    </div>
    <div class="d-flex feature-v1">
    <span class="wrap-icon icon-layers"></span>
    <div>
    <h3>Safe secure and reliable</h3>
    <p>Our repos and documentation are available for anyone to look at and scrutinize making it more resilient for all.</p>
    </div>
    </div>
    </div>
    </div>
</div>
</div>

<%= render 'staticpages/footer' %>

app/views/staticpages/index3.erb
<%= render 'staticpages/navbar_top'%>
<div class="jumbotron">
    <div class="container">
        <h1 class="display-4">WebCommandCenter</h1>
        <p class="lead">Deploying services has never been easier.</p>
        <hr class="my-4">
        <p>
            This service can be described as one step below a managed service provider.
            It is built for small to medium sized software teams and small businesses to help with productivity.
        </p>
        <p class="lead">
        <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
        </p>
    </div>
</div>

app/views/staticpages/pricing.erb
<!-- Navigation -->
<%= render 'staticpages/navbar_top' %>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Plan Pricing</h1>
    <div class="container-fluid">
    <div class="row">
    <div class="col-sm-8 offset-sm-2">
    <p class="lead">
        We price our plans based on techincal demands for services as well as the operating costs it takes for us to provide default support and high availability for our services.
        We also offer <%= link_to "Solutions", consulting_url %> to help you integrate these tools into your organization.
    </p>
    </div>
    </div>
    </div>
</div>

<div class="container mb-5">
    <div class="card-deck mb-3 text-center">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
        <h4 class="my-0 font-weight-normal">Minimal</h4>
        </div>
        <div class="card-body">
        <h1 class="card-title pricing-card-title">$15 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
            <li>A basic toolkit</li>
            <li>Limited to 2 Services</li>
        </ul>
        <%= link_to "Notify Me When Available!", contact_path(subject: "Notify me when the Minimal Plan is Ready!", description: "Notify me when the Minimal is ready!"), class:"btn btn-lg btn-block btn-warning" %>
        </div>
    </div>
    <div class="card mb-4 box-shadow">
        <div class="card-header">
        <h4 class="my-0 font-weight-normal">Personal</h4>
        </div>
        <div class="card-body">
        <h1 class="card-title pricing-card-title">$30 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
            <li>A full set of applications</li>
            <li>Limited to 4 Services</li>
        </ul>
        <%= link_to "Sign up for free", new_user_registration_path, class:"btn btn-lg btn-block btn-outline-primary" %>
        </div>
    </div>
    <div class="card mb-4 box-shadow">
        <div class="card-header">
        <h4 class="my-0 font-weight-normal">Personal Plus</h4>
        </div>
        <div class="card-body">
        <h1 class="card-title pricing-card-title">$45 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
            <li>Personal Plan + Juice</li>
            <li>Unimited Services</li>
        </ul>
        <%= link_to "Get Started", new_user_registration_path, class:"btn btn-lg btn-block btn-primary" %>
        </div>
    </div>
    </div>
</div>


<script>
    Holder.addTheme('thumb', {
    bg: '#55595c',
    fg: '#eceeef',
    text: 'Thumbnail'
    });
</script>
  
<div style="padding-top:5%;">
    <%= render 'staticpages/footer' %>
</div>

app/views/staticpages/privacy.erb
<!-- Navigation -->
<%= render 'staticpages/navbar_top'%>

<!-- Header -->
<header class="py-5 mb-5 about-header swirly-background" style="no-repeat center center; background-size: cover;">
<div class="container h-100">
    <div class="row h-100 align-items-center">
    <div class="col-lg-12">
        <h1 class="display-4 text-white mt-5 mb-2">Privacy</h1>
        <p class="lead mb-5 text-white">OurCompose never sells or abuses user data. We hold a strong stance on privacy and believe everyone should own their own data.</p>
    </div>
    </div>
</div>
</header>

<div class="container">
    <h1>Privacy Policy of Compositional Enterprises</h1>
    <p>Compositional Enterprises operates the ourcompose.com website, which provides the SERVICE.</p>
    <p>This page is used to inform website visitors regarding our policies with the collection, use, and disclosure of Personal Information if anyone decided to use our Service, the ourcompose.com website.</p>
    <p>If you choose to use our Service, then you agree to the collection and use of information in relation with this policy. The Personal Information that we collect are used for providing and improving the Service. We will not use or share your information with anyone except as described in this Privacy Policy.</p>
    <p>The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, which is accessible at <%= link_to "ourcompose.com/commandcenter/terms", terms_path %>, unless otherwise defined in this Privacy Policy.</p>
    <h2>Information Collection and Use</h2>
    <p>For a better experience while using our Service, we may require you to provide us with certain personally identifiable information, including but not limited to your name, phone number, and postal address. The information that we collect will be used to contact or identify you.</p>
    <h2>Log Data</h2>
    <p>We want to inform you that whenever you visit our Service, we collect information that your browser sends to us that is called Log Data. This Log Data may include information such as your computer's Internet Protocol (“IP”) address, browser version, pages of our Service that you visit, the time and date of your visit, the time spent on those pages, and other statistics.</p>
    <h2>Cookies</h2>
    <p>Cookies are files with small amount of data that is commonly used an anonymous unique identifier. These are sent to your browser from the website that you visit and are stored on your computer's hard drive.</p>
    <p>Our website uses these “cookies” to collection information and to improve our Service. You have the option to either accept or refuse these cookies, and know when a cookie is being sent to your computer. If you choose to refuse our cookies, you may not be able to use some portions of our Service.</p>
    <h2>Service Providers</h2>
    <p>We may employ third-party companies and individuals due to the following reasons:</p>
    <ul>
    <li>To facilitate our Service;</li>
    <li>To provide the Service on our behalf;</li>
    <li>To perform Service-related services; or</li>
    <li>To assist us in analyzing how our Service is used.</li>
    </ul>
    <p>We want to inform our Service users that these third parties have access to your Personal Information. The reason is to perform the tasks assigned to them on our behalf. However, they are obligated not to disclose or use the information for any other purpose.</p>
    <h2>Security</h2>
    <p>We value your trust in providing us your Personal Information, thus we are striving to use commercially acceptable means of protecting it. But remember that no method of transmission over the internet, or method of electronic storage is 100% secure and reliable, and we cannot guarantee its absolute security.</p>
    <h2>Links to Other Sites</h2>
    <p>Our Service may contain links to other sites. If you click on a third-party link, you will be directed to that site. Note that these external sites are not operated by us. Therefore, we strongly advise you to review the Privacy Policy of these websites. We have no control over, and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.</p>
    <p>Children's Privacy</p>
    <p>Our Services do not address anyone under the age of 13. We do not knowingly collect personal identifiable information from children under 13. In the case we discover that a child under 13 has provided us with personal information, we immediately delete this from our servers. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us so that we will be able to do necessary actions.</p>
    <h2>Changes to This Privacy Policy</h2>
    <p>We may update our Privacy Policy from time to time. Thus, we advise you to review this page periodically for any changes. We will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately, after they are posted on this page.</p>
    <h2>Contact Us</h2>
    <p>If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us.</p>
</div>


<div style="padding-top:5%;">
    <%= render 'staticpages/footer' %>
</div>