config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :skip => :registrations
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'users/confirmations'}

  authenticated :user do
    root to: "users#show", as: :authenticated_user
    resource :billing, controller: 'billing'
    namespace :billing do
      resource :customer, controller: 'customer'
      resources :charges
      resource :plans
    end
    #resources :services, path:'console'
    
    namespace :services do
      post 'deploy', to: 'deploy'
      get 'status', to: 'status'
    end

    resource :users, path:'account', only: [:show, :update]
    namespace :users, path:'account' do
      # Change this to something else...
      get 'applications', controller: 'applications', action: 'get_user_applications'
      post 'applications', controller: 'applications', action: 'select_applications'
      get 'settings', to: 'settings'
      match 'provision', to: 'provision', via: [:post] #needs to be a post request
      get 'provision_status', action: 'current_provision_status'
    end
  end

  authenticated :admin do
    devise_for :admins, only: [:registrations], controllers: { registrations: 'admins/registrations' }
    root to: "admins#show", as: :authenticated_admin
    namespace :admins do
      get 'user_statuses', to: 'users_statuses'
      get 'chart_data', to: 'chart_data', action:'chart_data'
      get 'validations', to: 'domain_validations', action:'domain_validations'
      post 'validate', to: 'validate_domain', action: 'validate_domain'
      post 'invalidate', to: 'invalidate_domain', action: 'invalidate_domain'
      get 'builds', to: 'build_tickets', action:'build_tickets'
      get 'decoms', to: 'decom_tickets', action:'decom_tickets'
      post 'mark_build_complete', to: 'mark_build_complete', action:'mark_build_complete'
      post 'mark_decom_complete', to: 'mark_decom_complete', action:'mark_decom_complete'

      get 'centerview', to:'centerview'
      namespace :centerview do
        get 'environments', to: 'environments'
        get 'subscriptions', to: 'subscriptions'
        get 'servers', to: 'servers'
        get 'domains', to: 'domains'
        get 'states', to: 'states'
      end

      resource :concierge, controller: "concierge"
      mount Blazer::Engine, at: "blazer"
    end
  end

  namespace :rundeck do
    post 'start', to: 'start', action: 'start'
    post 'complete', to: 'complete', action: 'complete'
    post 'fail', to: 'fail', action: 'fail'
    resource :options, only: [:show, :update]
    resource :datapoints, only: [:show] do
      get 'environment', action: 'environment_job_info'
      get 'instance', action: 'instance_job_info'
      get 'migration', action: 'migration_job_info'
    end
  end

  # unauthenticated :user do
  #   root "staticpages#index"
  # end

  root 'staticpages#index'

  get 'about', to: 'staticpages#about'
  get 'alternatives', to: 'staticpages#alternatives'
  get 'consulting', to: 'consultations#index'
  get 'contact', to: 'staticpages#contact'
  get 'home', to: 'staticpages#index'
  get 'pricing', to: 'staticpages#pricing'
  get 'privacy', to: 'staticpages#privacy'
  get 'products', to: 'products#list'
  get 'terms', to: 'staticpages#terms'

  post 'contact', to: 'staticpages#create_contact', as: 'contact_informations'
  namespace :products, path: "products" do
    get 'all', to: 'all'
  end
  resources :products, except: [:index]

  scope 'cases', module: "staticpages/cases", as: "cases" do
    get 'index', to: 'index'
    get 'students', to: 'students'
    get 'developers', to: 'developers'
    get 'projects', to: 'projects'
    get 'owners', to: 'owners'
    get 'leads', to: 'leads'
  end


  # resource :support
  # External Sites
  get "/docs" => redirect("https://compositionalenterprises.ourcompose.com/bookstack/books"), :as => :docs
  get "/gitlab" => redirect("https://gitlab.com/compositionalenterprises"), :as => :gitlab
  get "/forum" => redirect("https://reddit.com/r/ourcompose"), :as => :forum
  get "/podcast" => redirect("https://ourcomposecast.com"), :as => :podcast
  get "/roadmap" => redirect("https://compositionalenterprises.ourcompose.com/kanboard/public/board/245d06ce519a4deba6131ea58a65afa9efc0e6de584e04b08a81c4115322"), :as => :roadmap
end

app/models/product.rb
class Product < ApplicationRecord
    #
    # Current Products
    #  InProduction: 
    #    - Portal, Nextcloud, Bitwarden, Wordpress, Kanboard, Rundeck, Jekyll,
    #    - FireflyIII
    #  Coming Soon:
    #    - Email Server, User Management, Bitcoin Node, OAuth Server,
    #    - Discourse, Synapse, PHPmyLDAPAdmin, Gittea, OpenBazaar, 
    #    - NodeBB, Wireguard VPN, OpenVPN, Matomo
    #

    # in_production, coming_soon, name, image_link, short, html
    extend FriendlyId

    friendly_id :name, use: :slugged

    validates :name, presence: true, allow_blank: false

    before_save { self.name.downcase! }

    def self.all_in_production
        self.where(in_production: true)
    end

    def self.coming_soon
        self.where(coming_soon: true)
    end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_admin!, except: [:show, :list]

    def list
        @products_in_production = Product.where(in_production: true)
        @products_coming_soon = Product.where(coming_soon: true)
    end

    def all
        @all = Product.all
    end

    def show
        @product = Product.friendly.find(name_slugged)
    end

    def new
        @product = Product.new
    end

    def create
        Product.create(product_params)
        redirect_to products_url
    end

    def edit
        @product = Product.friendly.find(params[:id])
    end

    def update
        @product = Product.friendly.find(params[:id])
        @product.update!(product_params)
        redirect_to products_url
    end

    def destroy
        @product = Product.friendly.find(params[:id])
        @product.destroy
        redirect_to products_all_path
    end

    private

    def product_params
        params.require(:product).permit(:name, :short, :html, :in_production, :coming_soon)
    end

    def name_slugged
        params[:id].gsub("-", "")
    end
end

app/helpers/products_helper.rb
module ProductsHelper
    def self.picture_exists?(product)
        zendings = ["_logo.png", "_logo.jpg", "_logo.svg", "_logo.svg.png"]
        zendings.each do |ending|
            begin
                if ActionController::Base.helpers.asset_pack_path("media/images/products/" + product + ending).is_a?(String)
                    return true
                end
            rescue Webpacker::Manifest::MissingEntryError
                next
            end
        end
        return false
    end

    def self.picture_path(product)
        zendings = ["_logo.png", "_logo.jpg", "_logo.svg", "_logo.svg.png"]
        zendings.each do |ending|
            begin
                if ActionController::Base.helpers.asset_pack_path("media/images/products/" + product + ending).is_a?(String)
                    returnstr = "media/images/products/" + product + ending
                    return returnstr
                end
            rescue Webpacker::Manifest::MissingEntryError
                next
            end
        end
        return ""
    end
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class:"form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :short %>
        <%= f.text_area :short, class:"form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :html %><br>
        <%= f.text_area :html, class:"form-control" %>
    </div> 
    <div class="form-group">
        <%= f.label :in_production %><br>
        <%= f.check_box :in_production %>
    </div>
    <div class="form-group">
        <%= f.label :coming_soon %><br>
        <%= f.check_box :coming_soon %>
    </div>
    <div>
        <%= f.submit 'Submit', :class => "btn btn-primary" %>
    </div>
<% end %>

app/views/products/all.html.erb
<%= render 'staticpages/navbar_top' %>

<div class="container">
    <div class="display-3">All Products</div>
    <div class="row">
        <div class="col-sm-3"><%= link_to "New Product", new_product_path, class:"link" %></div>
    </div>
    <hr/>
    <% @all.each do |product| %>
        <div class="row">
            <div class="col-sm-2"><%= link_to product.name, product_path(product.name) %></div>
            <div class="col-sm-2"><%= link_to "edit", edit_product_path(product) %></div>
            <div class="col-sm-2"><%= link_to "delete", product_path(product), method: :delete %></div>
        </div>
    <% end %>
</div>

app/views/products/edit.html.erb
<%= render 'staticpages/navbar_top' %>

<div class="container">
    <div class="display-3">Edit <%= @product.name %> </div>
    <%= render 'form' %>
    <div class="mt-2">
    <%= link_to 'Destroy', @product,  method: :delete, class:"btn btn-danger", data: { confirm: 'Are you sure?' } %>
    </div>
</div>

app/views/products/list.html.erb
<!-- Navigation -->
<%= render 'staticpages/navbar_top' %>

<!-- Start Page Content -->
<div class="container mb-4" style="">

    <!-- Current Products and Services -->
    <div class="row">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="my-4 display-4">Products & Services</h1>
    </div>
    </div>
    <div class="card-columns m-3 mt-5">
        <% @products_in_production.each do |product| %>
            <div class="wow  fadeIn animated" data-wow-delay=".15s" style="visibility: visible; animation-delay: 0.15s; animation-name: fadeIn;">
                <%= link_to product_path(:id => product.name.gsub(' ', '-')), class:"project card text-dark" do %>
                <% if ProductsHelper.picture_exists?(product.name) == true %>
                    <img src="<%= asset_pack_path(ProductsHelper.picture_path(product.name)) %>" class="card-img-top" />
                <% end %>
                <div class="card-body">
                    <h5 id="git-for-wizards-name" class="card-title">
                        <i class="fab fa-github" data-toggle="tooltip" data-placement="bottom" data-delay="250" title="" data-original-title="GitHub Repository"></i><%= product.name.capitalize %>
                    </h5>
                    <p id="git-for-wizards-desc" class="card-text"><%= product.short %></p>
                </div>
                <% end %>
            </div>
        <% end %>
    </div>
    <!-- End Current Products and Services -->


    <!-- Coming Soon
    <div class="row">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="my-4 display-5">Coming Soon...</h1>
    </div>
    </div>
    <div class="card-columns m-3 mt-5">
        <% @products_coming_soon.each do |product| %>
            <div class="wow  fadeIn animated" data-wow-delay=".15s" style="visibility: visible; animation-delay: 0.15s; animation-name: fadeIn;">
                <%= link_to product_path(:id => product.name.gsub(' ', '-')), class:"project card text-dark" do %>
                <% if ProductsHelper.picture_exists?(product.name) == true %>
                    <img src="<% asset_pack_path(ProductsHelper.picture_path(product.name)) %>" class="card-img-top" />
                <% end %>
                <div class="card-body">
                    <h5 id="git-for-wizards-name" class="card-title">
                        <i class="fab fa-github" data-toggle="tooltip" data-placement="bottom" data-delay="250" title="" data-original-title="GitHub Repository"></i><%= product.name.capitalize %>
                    </h5>
                    <p id="git-for-wizards-desc" class="card-text"><%= product.short %></p>
                </div>
                <% end %>
            </div>
        <% end %>
    </div>
    End Coming Soon -->

</div>
<!-- End Page Content -->

<div style="padding-top:5%;">
    <%= render 'staticpages/footer' %>
</div>

app/views/products/new.html.erb
<%= render 'staticpages/navbar_top' %>
<div class="container">
    <div class="display-3">New Product</div>
    <%= render 'form' %>
</div>

app/views/products/show.html.erb
<%= render 'staticpages/navbar_top' %>

<div class="container">
    <h1 class="display-3"><%= @product.name.capitalize %></h1> 
    <div class="lead"><%= @product.short %></div>
    <%= link_to "Sign up and add #{ @product.name.capitalize } as a Service", new_user_registration_path, class:"btn btn-primary mt-2" %>
    <hr/>
    <div class=""> <%= @product.html.html_safe %></div>
</div>